version: '3.5'

volumes:
  db-data:
    external: false

services:
  cache:
    image: memcached:1.4-alpine

  db:
    image: postgres:11.9-alpine
    volumes:
      - db-data:/usr/local/pgsql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:

  app:
    env_file: .env
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/front-end
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - 'db'
    ports:
      - "3000:3000"

  # frontend:
  #   image: "node:14-alpine"
  #   working_dir: /usr/src/frontend
  #   volumes:
  #     - ./front-end:/usr/src/frontend
  #   command: "npm install"
  #   command: "npm run dev"
